name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          user: Pukimaa
          template: classic
          base: header, repositories, metadata
          config_timezone: America/New_York
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_lines: yes
          repositories_forks: yes
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_mode: recent
          plugin_music_limit: 4
          plugin_music_user: .user.login
          plugin_music_token: ${{ secrets.LASTFM_API_KEY }}
